version: "3.8"

services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo-network

  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - todo-network

volumes:
  postgres_data:
    driver: local

networks:
  todo-network:
    driver: bridge
